services:
  django:
    container_name: django
    image: backend-img
    env_file:
      - .env
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:7.2.5-alpine
    restart: always

  celery-worker:
    image: backend-img
    env_file:
      - .env
    restart: always
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    depends_on:
      - django
